acp_calendar/api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^working-days/(?P<start_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/(?P<end_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/$",
        views.CalendarCalculationsView.as_view(), {'calculation': 'working_days'}, name="working_days", ),
    url(r"^working-delta/(?P<start_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/(?P<days>[0-9]+)/$",
        views.CalendarCalculationsView.as_view(), {'calculation': 'working_delta'}, name="working_delta"),
    url(r"^working-month/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$",
        views.CalendarCalculationsView.as_view(), {'calculation': 'working_month'}, name="working_month"),
    url(r'^holiday-list/$', views.ACPHolidayListAPIView.as_view(), name='holiday-list'),
    url(r'^holiday-list/(?P<year>[0-9]{4})/$', views.ACPHolidayListAPIView.as_view(), name='holiday-list-year'),
]

acp_calendar/urls.py
from django.conf.urls import url, include

from .views import CalculatorView, CalendarView, HomeView, ACPHolidayListView

urlpatterns = [
    url(r'^list/$', ACPHolidayListView.as_view(), name='list'),
    url(r'^list/(?P<year>\d{4})/$', ACPHolidayListView.as_view(), name='list-year'),
    url(r'^calculator/', CalculatorView.as_view(), name='calculator'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^fiscal-year-calendar/(?P<fiscal_year>\d{4})', CalendarView.as_view(), name='fiscal-year-calendar'),
    url(r'^api/', include('acp_calendar.api.urls', namespace='calendar-api')),
]

example/example/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('acp_calendar.urls', namespace='calendar')),
]

acp_calendar/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class CalculatorForm(forms.Form):
    start_date = forms.DateField(label=_('Start date'))
    end_date = forms.DateField(label=_('End date'))

acp_calendar/api/views.py
from rest_framework import views
from rest_framework.generics import ListAPIView
from rest_framework.response import Response

from .serializers import ACPHolidaySerializer, StandardResultsSetPagination
from ..models import ACPHoliday, ACPCalendarException


class ACPHolidayListAPIView(ListAPIView):
    # queryset = ACPHoliday.objects.all()
    serializer_class = ACPHolidaySerializer
    pagination_class = StandardResultsSetPagination

    def get_queryset(self):
        year = self.kwargs.get('year', None)
        if year:
            return ACPHoliday.objects.filter(date__year=int(year))
        else:
            return ACPHoliday.objects.all()


class CalendarCalculationsView(views.APIView):
    def get(self, request, **kwargs):

        calculation = kwargs.pop('calculation', None)
        data = None
        if calculation == 'working_days':
            data = self.working_days(**kwargs)
        elif calculation == 'working_delta':
            data = self.working_delta(**kwargs)
        elif calculation == 'working_month':
            data = self.working_days_in_month(**kwargs)
        else:
            raise ACPCalendarException('Invalid Calculation')

        return Response(data)

    def working_days(self, start_date, end_date):
        results = {'start_date': start_date,
                   'end_date': end_date,
                   'days': '-1',
                   }
        try:
            days = ACPHoliday.get_working_days(start_date, end_date)
            results['days'] = str(days)
        except ACPCalendarException as e:
            results['error'] = str(e)

        return results

    def working_delta(self, start_date, days):
        results = {'start_date': start_date,
                   'end_date': None,
                   'days': days,
                   }
        try:
            end_date = ACPHoliday.working_delta(start_date, days)
            results['end_date'] = end_date
        except ACPCalendarException as e:
            results['error'] = str(e)

        return results

    def working_days_in_month(self, year, month):
        results = {'year': year,
                   'month': month,
                   'days': '-1',
                   }
        try:
            results['days'] = str(ACPHoliday.get_working_days_for_month(int(year), int(month)))
        except ACPCalendarException as e:
            results['error'] = str(e)
        return results

acp_calendar/views.py
from datetime import date

from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import View, ListView

from . import __version__ as current_version
from .exceptions import ACPCalendarException
from \
    .forms import CalculatorForm
from .models import ACPHoliday, FiscalYear
from .utils import compare_initial_data_against_db


class HomeView(View):
    template_name = 'acp_calendar/home.html'

    def get(self, request, *args, **kwargs):
        data = self._build_data_dict()
        return render(request, self.template_name, data)

    def post(self, request, *args, **kwargs):
        if 'update_fiscal_year' in request.POST:
            ACPHoliday.objects.update_fiscal_years()
            data = self._build_data_dict()
        elif 'check_initial_data' in request.POST:
            not_found = compare_initial_data_against_db()
            data = self._build_data_dict()
            data['not_found'] = not_found
        return render(request, self.template_name, data)

    def _build_data_dict(self):
        data = dict()
        data['first_holiday'] = ACPHoliday.objects.first()
        data['last_holiday'] = ACPHoliday.objects.last()
        data['holiday_count'] = ACPHoliday.objects.count()
        data['version'] = current_version
        # OrderNotes.objects.filter(item=item).values_list('shared_note', flat=True).distinct()
        # data['years'] = ACPHoliday.objects.order_by('-fiscal_year').distinct('fiscal_year').values('fiscal_year')
        data['years'] = ACPHoliday.objects.exclude(fiscal_year=0).order_by(
            '-fiscal_year'
        ).values_list('fiscal_year', flat=True).distinct()
        # if len(data['years']) == 1 and data['years'][0] == 0:
        #     data['years'] = []
        return data


class CalendarView(View):
    """
    View to generate a calendar for fiscal year containing the working days in every month
    of the fiscal year.
    """

    template_name = 'acp_calendar/fiscal_year_calendar.html'

    def get(self, request, *args, **kwargs):
        year = int(kwargs['fiscal_year'])
        fiscal_year = FiscalYear(year)
        data = dict()
        data['months'] = list()
        data['version'] = current_version
        data['fiscal_year'] = year
        data['working_days_in_fiscal_year'] = 0
        try:
            for month in fiscal_year.months_in_fiscal_year():
                month_data = dict()
                month_data['month'] = date(month[1], month[0], 1).strftime('%b')
                month_data['year'] = month[1]
                month_data['working_days'] = ACPHoliday.get_working_days_for_month(month[1], month[0])
                data['working_days_in_fiscal_year'] += month_data['working_days']
                data['months'].append(month_data)
            today = timezone.now().date()
            if today <= fiscal_year.end_date:
                data['remaining_working_days_in_fiscal_year'] = ACPHoliday.get_working_days(today, fiscal_year.end_date)
            else:
                data['remaining_working_days_in_fiscal_year'] = 0

            data['remaining_working_days_percentage'] = data['remaining_working_days_in_fiscal_year'] / data[
                'working_days_in_fiscal_year'] * 100
        except ACPCalendarException as e:
            data['errors'] = str(e)
        return render(request, self.template_name, data)


class CalculatorView(View):
    """
    View to calculate the amount of working day between two dates.
    """

    template_name = 'acp_calendar/calculator.html'

    def get(self, request, *args, **kwargs):
        form = CalculatorForm()
        data = {'form': form,
                'version': current_version}
        return render(request, self.template_name, data)

    def post(self, request, *args, **kwargs):
        calculator_form = CalculatorForm(request.POST)
        data = {'form': calculator_form,
                'working_days': None,
                'version': current_version}
        if calculator_form.is_valid():
            start_date = calculator_form.cleaned_data['start_date']
            end_date = calculator_form.cleaned_data['end_date']
            try:
                working_days = ACPHoliday.get_working_days(start_date, end_date)
                data['working_days'] = working_days
                return render(request, self.template_name, data)
            except ACPCalendarException as e:
                messages.add_message(request, messages.ERROR, str(e))
                return render(request, self.template_name, data)
        else:
            return render(request, self.template_name, data)


class ACPHolidayListView(ListView):
    model = ACPHoliday
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(ACPHolidayListView, self).get_context_data(**kwargs)
        if self.kwargs.get('year'):
            context['year'] = self.kwargs.get('year')
        return context

    def get_queryset(self):
        qs = super(ACPHolidayListView, self).get_queryset()
        if self.kwargs.get('year'):
            qs = qs.filter(date__year=int(self.kwargs.get('year')))
        return qs

acp_calendar/templates/acp_calendar/acpholiday_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block css %}
    {{ block.super }}
    <link href="{% static 'css/acp_calendar.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
    <div class="container">
    {% if year %}
        <h1>{% trans 'Holidays for' %} {{ year }}</h1>
    {% else %}
        <h1>{% trans 'Holidays' %}</h1>
    {% endif %}
    <table id="position_table" class="table table-striped table-bordered" cellspacing="0" width="50%">
            <thead>
            <tr>
                <th>{% trans 'Type' %}</th>
                <th>{% trans 'Date' %}</th>
                <th>{% trans 'Fiscal Year' %}</th>
            </tr>
            </thead>

            <tbody>
            {% for holiday in acpholiday_list %}
                <tr>

                    <td>{{ holiday.holiday_type.name }}  &#x1F1F5; &#x1F1E6;</td>
                    <td>{{ holiday.date }}</td>
                    <td>{{ holiday.fiscal_year }}</td>

                </tr>
            {% endfor %}
            </tbody>
        </table>


    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
    </div>
{% endblock %}

acp_calendar/templates/acp_calendar/calculator.html
{% extends "base.html" %}
{% load static i18n %}
{% block css %}
  {{ block.super }}
  <link href="{% static 'css/acp_calendar.css' %}" rel="stylesheet"/>
{% endblock css %}
{% block content %}
<h2>Calculator</h2>
<div>
  Enter date in YYYY-MM-DD format. For example for january 5th 2016 type 2016-01-05.
</div>

<form action="" method="post">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-6">
      <div class="form-group {%if form.start_date.errors %}has-danger{%endif%}">
        <label for="{{ form.start_date.id_for_label }}" class="control-label">{{ form.start_date.label }}</label>
        <input
          type="text" value="{{ form.start_date.value }}" title=""
          placeholder="{{ form.start_date.label }}" name="start_date"
          id="{{ form.start_date.id_for_label }}" class="form-control datepicker"/>
      </div>
      {% for error in form.start_date.errors %}
          <p class="bg-danger">{{ error }} </p>
        {% endfor %}
    </div>
     </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group {%if form.end_date.errors %}has-danger{%endif%}">

        <label for="{{ form.end_date.id_for_label }}" class="control-label">{{ form.end_date.label }}</label>
        <input
          type="text" value="{{ form.end_date.value }}" title=""
          placeholder="{{ form.end_date.label }}" name="end_date"
          id="{{ form.end_date.id_for_label }}" class="form-control datepicker"/>
      </div>
      {% for error in form.end_date.errors %}
          <p class="bg-danger">{{ error }} </p>
        {% endfor %}
    </div>
    </div>

    <input class="btn btn-primary" role="button" type="submit" value="{% trans 'Calculate' %}"/>

</form>

{% if  working_days%}
     <h3>
{{ working_days }} working days
    </h3>
{% endif %}

<div class="version">Version: {{ version }}</div>
{% endblock content %}
{% block javascript %}
{{ block.super }}
    <script>
        $.datepicker.setDefaults({
            showOn: "both",
        });
        $.datepicker.setDefaults($.datepicker.regional["{{ LANGUAGE_CODE }}"]);
        $(".datepicker").datepicker({
            dateFormat: "yy-mm-dd",
            altFormat: "yy-mm-dd"
        });
    </script>
{% endblock javascript %}

acp_calendar/templates/acp_calendar/fiscal_year_calendar.html
{% extends "base.html" %}
{% load static i18n %}
{% block css %}
    {{ block.super }}
    <link href="{% static 'css/acp_calendar.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
    <h2>Fiscal Year Calendar {{ fiscal_year }}</h2>
    {% if errors %}
        <div>
            <h3>Error</h3>
            <div>{{ errors }}</div>
        </div>

    {% else %}

        <div class="row">
            {% for month in months|slice:":3" %}
                {% include "acp_calendar/snippets/month_snippet.html" %}
            {% endfor %}
        </div>

        <div class="row">
            {% for month in months|slice:"3:6" %}
                {% include "acp_calendar/snippets/month_snippet.html" %}
            {% endfor %}
        </div>
        <div class="row">
            {% for month in months|slice:"6:9" %}
                 {% include "acp_calendar/snippets/month_snippet.html" %}
            {% endfor %}
        </div>
        <div class="row">
            {% for month in months|slice:"9:12" %}
                 {% include "acp_calendar/snippets/month_snippet.html" %}
            {% endfor %}
        </div>
        <div class="row">
            <div>Remaining working days: {{ remaining_working_days_in_fiscal_year }} ({{ remaining_working_days_percentage|floatformat:2 }}% remaining)</div>
            <div>Working days: {{ working_days_in_fiscal_year }}</div>
        </div>
    {% endif %}
    <div class="version">Version: {{ version }}</div>
{% endblock content %}

acp_calendar/templates/acp_calendar/home.html
{% extends "base.html" %}
{% load static i18n %}
{% block css %}
{{ block.super }}
<link href="{% static 'css/acp_calendar.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
<h2>Fiscal Years</h2>
<form action="" method="post">
  {% csrf_token %}
  <input class="btn btn-primary" role="button" type="submit" name="update_fiscal_year"
         value="{% trans 'Update Fiscal Year' %}">
  <input class="btn btn-primary" role="button" type="submit" name="check_initial_data"
         value="{% trans 'Check Initial Data' %}">
</form>
<div>
  <div class="row">
    <div class="col-md-4">First date: {{ first_holiday.date }}</div>
    <div class="col-md-4">Last date: {{ last_holiday.date }}</div>
    <div class="col-md-4">{% trans 'Holiday count' %}: {{ holiday_count }}</div>
  </div>
</div>
<div>
  {% if years.count != 0 %}
  <div class="row">
  {% for year in years %}

    <div class="col-md-3">
      <a href="{% url 'calendar:fiscal-year-calendar'  year %}">
        Fiscal Year {{ year }}
      </a>
    </div>

  {% endfor %}
  </div>
  {% endif %}
</div>
{% for not_loaded in not_found %}
<div class="row">
  <div class="col-md-4">
    {{ not_loaded.date }}
  </div>
  <div class="col-md-4">
    {{ not_loaded.holiday_type }}
  </div>
</div>
{% endfor %}
    <h2>Utilities</h2>
    <div>
  <a href="{% url 'calendar:calculator' %}">
    Working Days Calculator
  </a>
</div>
<h2>API Calls</h2>
<div>
  <a href="{% url 'calendar:calendar-api:holiday-list' %}">
    Holiday List
  </a>
</div>
<div>
  <a href="{% url 'calendar:calendar-api:holiday-list-year' 2016%}">
    Holiday List for 2016
  </a>
</div>
<div>
  <a href="{% url 'calendar:calendar-api:working_month' 2016 11%}">
    Holiday month for 2016 on november
  </a>
</div>
<div>
  <a href="{% url 'calendar:calendar-api:working_delta' '2015-11-01' 30%}">
    Date for 30 working days after Nov. 1st 2015
  </a>
</div>
<div>
  <a href="{% url 'calendar:calendar-api:working_days' '2015-11-01' '2015-12-31' %}">
    Working days between  Nov. 1st 2015 and Dec. 31st 2015
  </a>
</div>
<div class="version">Version: {{ version }}</div>
{% endblock content %}