acp_calendar/api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^working-days/(?P<start_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/(?P<end_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/$",
        views.CalendarCalculationsView.as_view(), {'calculation': 'working_days'}, name="working_days", ),
    url(r"^working-delta/(?P<start_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/(?P<days>[0-9]+)/$",
        views.CalendarCalculationsView.as_view(), {'calculation': 'working_delta'}, name="working_delta"),
    url(r"^working-month/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$",
        views.CalendarCalculationsView.as_view(), {'calculation': 'working_month'}, name="working_month"),
    url(r'^holiday-list/$', views.ACPHolidayListAPIView.as_view(), name='holiday-list'),
    url(r'^holiday-list/(?P<year>[0-9]{4})/$', views.ACPHolidayListAPIView.as_view(), name='holiday-list-year'),
]

acp_calendar/urls.py
from django.conf.urls import url, include

from .views import CalculatorView, CalendarView, HomeView, ACPHolidayListView

urlpatterns = [
    url(r'^list/$', ACPHolidayListView.as_view(), name='list'),
    url(r'^list/(?P<year>\d{4})/$', ACPHolidayListView.as_view(), name='list-year'),
    url(r'^calculator/', CalculatorView.as_view(), name='calculator'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^fiscal-year-calendar/(?P<fiscal_year>\d{4})', CalendarView.as_view(), name='fiscal-year-calendar'),
    url(r'^api/', include('acp_calendar.api.urls', namespace='calendar-api')),
]

example/example/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('acp_calendar.urls', namespace='calendar')),
]

acp_calendar/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class CalculatorForm(forms.Form):
    start_date = forms.DateField(label=_('Start date'))
    end_date = forms.DateField(label=_('End date'))

acp_calendar/api/views.py
from rest_framework import views
from rest_framework.generics import ListAPIView
from rest_framework.response import Response

from .serializers import ACPHolidaySerializer, StandardResultsSetPagination
from ..models import ACPHoliday, ACPCalendarException


class ACPHolidayListAPIView(ListAPIView):
    # queryset = ACPHoliday.objects.all()
    serializer_class = ACPHolidaySerializer
    pagination_class = StandardResultsSetPagination

    def get_queryset(self):
        year = self.kwargs.get('year', None)
        if year:
            return ACPHoliday.objects.filter(date__year=int(year))
        else:
            return ACPHoliday.objects.all()


class CalendarCalculationsView(views.APIView):
    def get(self, request, **kwargs):

        calculation = kwargs.pop('calculation', None)
        data = None
        if calculation == 'working_days':
            data = self.working_days(**kwargs)
        elif calculation == 'working_delta':
            data = self.working_delta(**kwargs)
        elif calculation == 'working_month':
            data = self.working_days_in_month(**kwargs)
        else:
            raise ACPCalendarException('Invalid Calculation')

        return Response(data)

    def working_days(self, start_date, end_date):
        results = {'start_date': start_date,
                   'end_date': end_date,
                   'days': '-1',
                   }
        try:
            days = ACPHoliday.get_working_days(start_date, end_date)
            results['days'] = str(days)
        except ACPCalendarException as e:
            results['error'] = str(e)

        return results

    def working_delta(self, start_date, days):
        results = {'start_date': start_date,
                   'end_date': None,
                   'days': days,
                   }
        try:
            end_date = ACPHoliday.working_delta(start_date, days)
            results['end_date'] = end_date
        except ACPCalendarException as e:
            results['error'] = str(e)

        return results

    def working_days_in_month(self, year, month):
        results = {'year': year,
                   'month': month,
                   'days': '-1',
                   }
        try:
            results['days'] = str(ACPHoliday.get_working_days_for_month(int(year), int(month)))
        except ACPCalendarException as e:
            results['error'] = str(e)
        return results

acp_calendar/views.py
from datetime import date

from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import View, ListView

from . import __version__ as current_version
from .exceptions import ACPCalendarException
from \
    .forms import CalculatorForm
from .models import ACPHoliday, FiscalYear
from .utils import compare_initial_data_against_db


class HomeView(View):
    template_name = 'acp_calendar/home.html'

    def get(self, request, *args, **kwargs):
        data = self._build_data_dict()
        return render(request, self.template_name, data)

    def post(self, request, *args, **kwargs):
        if 'update_fiscal_year' in request.POST:
            ACPHoliday.objects.update_fiscal_years()
            data = self._build_data_dict()
        elif 'check_initial_data' in request.POST:
            not_found = compare_initial_data_against_db()
            data = self._build_data_dict()
            data['not_found'] = not_found
        return render(request, self.template_name, data)

    def _build_data_dict(self):
        data = dict()
        data['first_holiday'] = ACPHoliday.objects.first()
        data['last_holiday'] = ACPHoliday.objects.last()
        data['holiday_count'] = ACPHoliday.objects.count()
        data['version'] = current_version
        # OrderNotes.objects.filter(item=item).values_list('shared_note', flat=True).distinct()
        # data['years'] = ACPHoliday.objects.order_by('-fiscal_year').distinct('fiscal_year').values('fiscal_year')
        data['years'] = ACPHoliday.objects.exclude(fiscal_year=0).order_by(
            '-fiscal_year'
        ).values_list('fiscal_year', flat=True).distinct()
        # if len(data['years']) == 1 and data['years'][0] == 0:
        #     data['years'] = []
        return data


class CalendarView(View):
    """
    View to generate a calendar for fiscal year containing the working days in every month
    of the fiscal year.
    """

    template_name = 'acp_calendar/fiscal_year_calendar.html'

    def get(self, request, *args, **kwargs):
        year = int(kwargs['fiscal_year'])
        fiscal_year = FiscalYear(year)
        data = dict()
        data['months'] = list()
        data['version'] = current_version
        data['fiscal_year'] = year
        data['working_days_in_fiscal_year'] = 0
        try:
            for month in fiscal_year.months_in_fiscal_year():
                month_data = dict()
                month_data['month'] = date(month[1], month[0], 1).strftime('%b')
                month_data['year'] = month[1]
                month_data['working_days'] = ACPHoliday.get_working_days_for_month(month[1], month[0])
                data['working_days_in_fiscal_year'] += month_data['working_days']
                data['months'].append(month_data)
            today = timezone.now().date()
            if today <= fiscal_year.end_date:
                data['remaining_working_days_in_fiscal_year'] = ACPHoliday.get_working_days(today, fiscal_year.end_date)
            else:
                data['remaining_working_days_in_fiscal_year'] = 0

            data['remaining_working_days_percentage'] = data['remaining_working_days_in_fiscal_year'] / data[
                'working_days_in_fiscal_year'] * 100
        except ACPCalendarException as e:
            data['errors'] = str(e)
        return render(request, self.template_name, data)


class CalculatorView(View):
    """
    View to calculate the amount of working day between two dates.
    """

    template_name = 'acp_calendar/calculator.html'

    def get(self, request, *args, **kwargs):
        form = CalculatorForm()
        data = {'form': form,
                'version': current_version}
        return render(request, self.template_name, data)

    def post(self, request, *args, **kwargs):
        calculator_form = CalculatorForm(request.POST)
        data = {'form': calculator_form,
                'working_days': None,
                'version': current_version}
        if calculator_form.is_valid():
            start_date = calculator_form.cleaned_data['start_date']
            end_date = calculator_form.cleaned_data['end_date']
            try:
                working_days = ACPHoliday.get_working_days(start_date, end_date)
                data['working_days'] = working_days
                return render(request, self.template_name, data)
            except ACPCalendarException as e:
                messages.add_message(request, messages.ERROR, str(e))
                return render(request, self.template_name, data)
        else:
            return render(request, self.template_name, data)


class ACPHolidayListView(ListView):
    model = ACPHoliday
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(ACPHolidayListView, self).get_context_data(**kwargs)
        if self.kwargs.get('year'):
            context['year'] = self.kwargs.get('year')
        return context

    def get_queryset(self):
        qs = super(ACPHolidayListView, self).get_queryset()
        if self.kwargs.get('year'):
            qs = qs.filter(date__year=int(self.kwargs.get('year')))
        return qs

acp_calendar/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <title>{% block title %}acp_calendar_project{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
              crossorigin="anonymous">

        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"/>
        <!-- Your stuff: Third-party css libraries go here -->

        <!-- This file store project specific CSS -->
        <link href="{% static 'css/project.css' %}" rel="stylesheet"/>
    {% endblock %}

</head>

<body>

<div class="m-b">
    <nav class="navbar navbar-inverse">
        <div class="container">
            <a class="navbar-brand" href="/">ACP Calendar Test</a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-navbar-collapse-1">
                &#9776;
            </button>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'calendar:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">About</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav pull-xs-right">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{% url 'users:detail' request.user.username %}">{% trans "My Profile" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">{% trans "Logout" %}</a>
                        </li>
                    {% else %}

                        <li class="nav-item">
                            <a id="log-in-link" class="nav-link" href="">{% trans "Log In" %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>


<div class="container">

    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
        {% endfor %}
    {% endif %}

    {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
    {% endblock content %}

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}
    <!-- Latest JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

    <!-- Tether - a requirement for Bootstrap tooltips -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <!-- Your stuff: Third-party javascript libraries go here -->

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/project.js' %}"></script>
{% endblock javascript %}
</body>
</html>